# Generated by Django 4.1.5 on 2023-01-21 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minha_dashboard', '0018_alter_vendas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 12, 37, 5, 689978)),
        ),
    ]
