# Generated by Django 4.1.5 on 2023-02-01 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0023_alter_vendas_data_alter_vendas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 17, 11, 1, 156499)),
        ),
    ]
